theme: jekyll-theme-hacker
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
yandex_url: https://money.yandex.ru/quickpay/shop-widget?writer=seller&targets=Support%20me%2C%20%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0&targets-hint=&default-sum=10&button-text=14&payment-type-choice=on&mobile-payment-type-choice=on&mail=on&hint=&successURL=https%3A%2F%2Funknownproject.github.io%2F&quickpay=shop&account=41001263743821
