title: Unknownproject's lair
author: unknownproject
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
Unknownproject is a programmer and reverse engineer.
Copyright material used under fair use for research and improvement purposes.
show_excerpts: false # set to true to show excerpts on the homepage
minima:
  date_format: "%b %-d, %Y"
social_links:
  github:  unknownproject
  rss: rss
  youtube_channel: UCCjgivnEXTz7vLE4n894Wsg
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
